// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feedbacks.proto

package feedbacks

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseOk struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseOk) Reset()         { *m = ResponseOk{} }
func (m *ResponseOk) String() string { return proto.CompactTextString(m) }
func (*ResponseOk) ProtoMessage()    {}
func (*ResponseOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{0}
}

func (m *ResponseOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOk.Unmarshal(m, b)
}
func (m *ResponseOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOk.Marshal(b, m, deterministic)
}
func (m *ResponseOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOk.Merge(m, src)
}
func (m *ResponseOk) XXX_Size() int {
	return xxx_messageInfo_ResponseOk.Size(m)
}
func (m *ResponseOk) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOk.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOk proto.InternalMessageInfo

func (m *ResponseOk) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ParamsApp struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AppVersion           string   `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Rate                 string   `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Reasons              []int32  `protobuf:"varint,4,rep,packed,name=reasons,proto3" json:"reasons,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamsApp) Reset()         { *m = ParamsApp{} }
func (m *ParamsApp) String() string { return proto.CompactTextString(m) }
func (*ParamsApp) ProtoMessage()    {}
func (*ParamsApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{1}
}

func (m *ParamsApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamsApp.Unmarshal(m, b)
}
func (m *ParamsApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamsApp.Marshal(b, m, deterministic)
}
func (m *ParamsApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsApp.Merge(m, src)
}
func (m *ParamsApp) XXX_Size() int {
	return xxx_messageInfo_ParamsApp.Size(m)
}
func (m *ParamsApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsApp.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsApp proto.InternalMessageInfo

func (m *ParamsApp) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ParamsApp) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *ParamsApp) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *ParamsApp) GetReasons() []int32 {
	if m != nil {
		return m.Reasons
	}
	return nil
}

func (m *ParamsApp) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type ParamsStore struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Rate                 string   `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Reasons              []int32  `protobuf:"varint,3,rep,packed,name=reasons,proto3" json:"reasons,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	StoreId              int32    `protobuf:"varint,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamsStore) Reset()         { *m = ParamsStore{} }
func (m *ParamsStore) String() string { return proto.CompactTextString(m) }
func (*ParamsStore) ProtoMessage()    {}
func (*ParamsStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{2}
}

func (m *ParamsStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamsStore.Unmarshal(m, b)
}
func (m *ParamsStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamsStore.Marshal(b, m, deterministic)
}
func (m *ParamsStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsStore.Merge(m, src)
}
func (m *ParamsStore) XXX_Size() int {
	return xxx_messageInfo_ParamsStore.Size(m)
}
func (m *ParamsStore) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsStore.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsStore proto.InternalMessageInfo

func (m *ParamsStore) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ParamsStore) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *ParamsStore) GetReasons() []int32 {
	if m != nil {
		return m.Reasons
	}
	return nil
}

func (m *ParamsStore) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ParamsStore) GetStoreId() int32 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

type ParamsOrder struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rate                 string   `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Reasons              []int32  `protobuf:"varint,3,rep,packed,name=reasons,proto3" json:"reasons,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	StoreId              int32    `protobuf:"varint,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamsOrder) Reset()         { *m = ParamsOrder{} }
func (m *ParamsOrder) String() string { return proto.CompactTextString(m) }
func (*ParamsOrder) ProtoMessage()    {}
func (*ParamsOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{3}
}

func (m *ParamsOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamsOrder.Unmarshal(m, b)
}
func (m *ParamsOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamsOrder.Marshal(b, m, deterministic)
}
func (m *ParamsOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsOrder.Merge(m, src)
}
func (m *ParamsOrder) XXX_Size() int {
	return xxx_messageInfo_ParamsOrder.Size(m)
}
func (m *ParamsOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsOrder proto.InternalMessageInfo

func (m *ParamsOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ParamsOrder) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *ParamsOrder) GetReasons() []int32 {
	if m != nil {
		return m.Reasons
	}
	return nil
}

func (m *ParamsOrder) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ParamsOrder) GetStoreId() int32 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

type Reason struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId           int32    `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reason) Reset()         { *m = Reason{} }
func (m *Reason) String() string { return proto.CompactTextString(m) }
func (*Reason) ProtoMessage()    {}
func (*Reason) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{4}
}

func (m *Reason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reason.Unmarshal(m, b)
}
func (m *Reason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reason.Marshal(b, m, deterministic)
}
func (m *Reason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reason.Merge(m, src)
}
func (m *Reason) XXX_Size() int {
	return xxx_messageInfo_Reason.Size(m)
}
func (m *Reason) XXX_DiscardUnknown() {
	xxx_messageInfo_Reason.DiscardUnknown(m)
}

var xxx_messageInfo_Reason proto.InternalMessageInfo

func (m *Reason) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reason) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Reason) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{5}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type RequestChoices struct {
	CategoryId           int32    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChoices) Reset()         { *m = RequestChoices{} }
func (m *RequestChoices) String() string { return proto.CompactTextString(m) }
func (*RequestChoices) ProtoMessage()    {}
func (*RequestChoices) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{6}
}

func (m *RequestChoices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChoices.Unmarshal(m, b)
}
func (m *RequestChoices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChoices.Marshal(b, m, deterministic)
}
func (m *RequestChoices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChoices.Merge(m, src)
}
func (m *RequestChoices) XXX_Size() int {
	return xxx_messageInfo_RequestChoices.Size(m)
}
func (m *RequestChoices) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChoices.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChoices proto.InternalMessageInfo

func (m *RequestChoices) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type ResponseReasons struct {
	Result               []*Reason `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseReasons) Reset()         { *m = ResponseReasons{} }
func (m *ResponseReasons) String() string { return proto.CompactTextString(m) }
func (*ResponseReasons) ProtoMessage()    {}
func (*ResponseReasons) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{7}
}

func (m *ResponseReasons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseReasons.Unmarshal(m, b)
}
func (m *ResponseReasons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseReasons.Marshal(b, m, deterministic)
}
func (m *ResponseReasons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseReasons.Merge(m, src)
}
func (m *ResponseReasons) XXX_Size() int {
	return xxx_messageInfo_ResponseReasons.Size(m)
}
func (m *ResponseReasons) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseReasons.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseReasons proto.InternalMessageInfo

func (m *ResponseReasons) GetResult() []*Reason {
	if m != nil {
		return m.Result
	}
	return nil
}

type ResponseCategories struct {
	Result               []*Category `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseCategories) Reset()         { *m = ResponseCategories{} }
func (m *ResponseCategories) String() string { return proto.CompactTextString(m) }
func (*ResponseCategories) ProtoMessage()    {}
func (*ResponseCategories) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{8}
}

func (m *ResponseCategories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCategories.Unmarshal(m, b)
}
func (m *ResponseCategories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCategories.Marshal(b, m, deterministic)
}
func (m *ResponseCategories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCategories.Merge(m, src)
}
func (m *ResponseCategories) XXX_Size() int {
	return xxx_messageInfo_ResponseCategories.Size(m)
}
func (m *ResponseCategories) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCategories.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCategories proto.InternalMessageInfo

func (m *ResponseCategories) GetResult() []*Category {
	if m != nil {
		return m.Result
	}
	return nil
}

type ParamsReasonsByOrder struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamsReasonsByOrder) Reset()         { *m = ParamsReasonsByOrder{} }
func (m *ParamsReasonsByOrder) String() string { return proto.CompactTextString(m) }
func (*ParamsReasonsByOrder) ProtoMessage()    {}
func (*ParamsReasonsByOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada70ba69b487c57, []int{9}
}

func (m *ParamsReasonsByOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamsReasonsByOrder.Unmarshal(m, b)
}
func (m *ParamsReasonsByOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamsReasonsByOrder.Marshal(b, m, deterministic)
}
func (m *ParamsReasonsByOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsReasonsByOrder.Merge(m, src)
}
func (m *ParamsReasonsByOrder) XXX_Size() int {
	return xxx_messageInfo_ParamsReasonsByOrder.Size(m)
}
func (m *ParamsReasonsByOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsReasonsByOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsReasonsByOrder proto.InternalMessageInfo

func (m *ParamsReasonsByOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponseOk)(nil), "feedbacks.ResponseOk")
	proto.RegisterType((*ParamsApp)(nil), "feedbacks.ParamsApp")
	proto.RegisterType((*ParamsStore)(nil), "feedbacks.ParamsStore")
	proto.RegisterType((*ParamsOrder)(nil), "feedbacks.ParamsOrder")
	proto.RegisterType((*Reason)(nil), "feedbacks.Reason")
	proto.RegisterType((*Category)(nil), "feedbacks.Category")
	proto.RegisterType((*RequestChoices)(nil), "feedbacks.RequestChoices")
	proto.RegisterType((*ResponseReasons)(nil), "feedbacks.ResponseReasons")
	proto.RegisterType((*ResponseCategories)(nil), "feedbacks.ResponseCategories")
	proto.RegisterType((*ParamsReasonsByOrder)(nil), "feedbacks.ParamsReasonsByOrder")
}

func init() { proto.RegisterFile("proto/feedbacks.proto", fileDescriptor_ada70ba69b487c57) }

var fileDescriptor_ada70ba69b487c57 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x6f, 0xd3, 0x3e,
	0x14, 0x6f, 0x9a, 0xa6, 0x3f, 0x5e, 0xbf, 0xea, 0x57, 0x98, 0x6e, 0x0a, 0x1d, 0x68, 0x95, 0x4f,
	0x45, 0x48, 0x2d, 0x1b, 0x1c, 0x38, 0x70, 0xd9, 0xa6, 0x21, 0xf5, 0x80, 0x8a, 0x8c, 0xc4, 0x81,
	0xcb, 0x94, 0x36, 0x6f, 0x25, 0x6a, 0x1a, 0x07, 0xdb, 0x45, 0xea, 0xdf, 0x80, 0x38, 0xc0, 0x5f,
	0x8c, 0x6c, 0xc7, 0x5d, 0xba, 0x76, 0x85, 0x13, 0xb7, 0xbc, 0xe7, 0xcf, 0xaf, 0xf8, 0xd9, 0x86,
	0xa3, 0x5c, 0x70, 0xc5, 0x47, 0xb7, 0x88, 0xf1, 0x34, 0x9a, 0x2d, 0xe4, 0xd0, 0xd4, 0xa4, 0xb5,
	0x69, 0xf4, 0x4e, 0xe6, 0x9c, 0xcf, 0x53, 0x1c, 0x99, 0x85, 0xe9, 0xea, 0x76, 0x84, 0xcb, 0x5c,
	0xad, 0x2d, 0x8e, 0x3e, 0x05, 0x60, 0x28, 0x73, 0x9e, 0x49, 0x9c, 0x2c, 0x48, 0x07, 0xaa, 0x7c,
	0x11, 0x7a, 0x7d, 0x6f, 0xd0, 0x64, 0x55, 0xbe, 0xa0, 0x3f, 0x3d, 0x68, 0x7d, 0x88, 0x44, 0xb4,
	0x94, 0x17, 0x79, 0x4e, 0x4e, 0xa0, 0x35, 0x4b, 0x13, 0xcc, 0xd4, 0x4d, 0x12, 0x1b, 0x90, 0xcf,
	0x9a, 0xb6, 0x31, 0x8e, 0xc9, 0x29, 0xb4, 0xa3, 0x3c, 0xbf, 0xf9, 0x86, 0x42, 0x26, 0x3c, 0x0b,
	0xab, 0x7d, 0x6f, 0xd0, 0x62, 0x10, 0xe5, 0xf9, 0x27, 0xdb, 0x21, 0x04, 0x6a, 0x22, 0x52, 0x18,
	0xfa, 0x66, 0xc5, 0x7c, 0x93, 0x10, 0x1a, 0x02, 0x23, 0xc9, 0x33, 0x19, 0xd6, 0xfa, 0xfe, 0x20,
	0x60, 0xae, 0xd4, 0x2b, 0x33, 0xbe, 0x5c, 0x62, 0xa6, 0xc2, 0xc0, 0x10, 0x5c, 0x49, 0x7f, 0x78,
	0xd0, 0xb6, 0x99, 0x3e, 0x2a, 0x2e, 0xf0, 0x70, 0x2a, 0x67, 0x5a, 0xdd, 0x6f, 0xea, 0x3f, 0x68,
	0x5a, 0xdb, 0x32, 0x25, 0x4f, 0xa0, 0x29, 0xb5, 0x9b, 0xf6, 0xd0, 0x79, 0x02, 0xd6, 0x30, 0xf5,
	0x38, 0xa6, 0xdf, 0x37, 0x79, 0x26, 0x22, 0x46, 0xa1, 0xa1, 0x5c, 0x7f, 0xb8, 0x38, 0x2d, 0xd6,
	0x30, 0xf5, 0xbf, 0x49, 0x33, 0x81, 0x3a, 0x33, 0x7c, 0x3d, 0xcb, 0x22, 0x41, 0xc0, 0xaa, 0x49,
	0x4c, 0xba, 0x10, 0xa8, 0x44, 0xa5, 0xce, 0xdd, 0x16, 0x7a, 0x6c, 0xb3, 0x48, 0xe1, 0x9c, 0x8b,
	0xb5, 0x56, 0xf3, 0x0d, 0x1c, 0x5c, 0x6b, 0x1c, 0xd3, 0x97, 0xd0, 0xbc, 0x2a, 0xaa, 0xbf, 0x93,
	0xa4, 0x67, 0xd0, 0x61, 0xf8, 0x75, 0x85, 0x52, 0x5d, 0x7d, 0xe1, 0xc9, 0x0c, 0xe5, 0x7d, 0x13,
	0x6f, 0xc7, 0xe4, 0x2d, 0xfc, 0xef, 0x4e, 0x21, 0x2b, 0xfe, 0xfe, 0x39, 0xd4, 0x05, 0xca, 0x55,
	0xaa, 0x42, 0xaf, 0xef, 0x0f, 0xda, 0xe7, 0x8f, 0x86, 0x77, 0x47, 0xdc, 0x62, 0x58, 0x01, 0xa0,
	0x17, 0x40, 0x1c, 0xbb, 0x88, 0x9a, 0xa0, 0x24, 0x2f, 0xee, 0x09, 0x3c, 0x2e, 0x09, 0xb8, 0x3f,
	0xda, 0x48, 0x9c, 0x41, 0xd7, 0xce, 0xb0, 0xb0, 0xbf, 0x5c, 0xff, 0x69, 0x98, 0xe7, 0xbf, 0x7c,
	0xa8, 0xbf, 0xe7, 0xd3, 0x24, 0x45, 0xf2, 0x1a, 0x7c, 0x7d, 0x3f, 0xba, 0x25, 0x87, 0xcd, 0xad,
	0xe9, 0x1d, 0x6d, 0x05, 0x77, 0x57, 0x8d, 0x56, 0xc8, 0x1b, 0x08, 0xec, 0x09, 0x3e, 0xde, 0xe1,
	0x99, 0xfe, 0x41, 0xa6, 0x8d, 0xb7, 0xcb, 0x34, 0xfd, 0x87, 0x99, 0xd7, 0x00, 0xa5, 0x2d, 0x3a,
	0x1e, 0xda, 0xa7, 0x61, 0xe8, 0x9e, 0x86, 0xe1, 0xb5, 0x7e, 0x1a, 0x7a, 0xcf, 0xf6, 0xd0, 0xef,
	0x68, 0xb4, 0x42, 0x26, 0x7a, 0xc4, 0x5b, 0x1b, 0x75, 0xba, 0x93, 0x64, 0x1b, 0xd0, 0xeb, 0xed,
	0xd1, 0x2c, 0x20, 0xb4, 0x42, 0xde, 0x95, 0x04, 0xdd, 0xa6, 0xec, 0xcf, 0x76, 0x50, 0xe7, 0xb2,
	0xf3, 0xf9, 0xbf, 0x79, 0xe9, 0x31, 0x9c, 0xd6, 0x0d, 0xfb, 0xd5, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x2a, 0xe6, 0xa7, 0x26, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MobileClient is the client API for Mobile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MobileClient interface {
	App(ctx context.Context, in *ParamsApp, opts ...grpc.CallOption) (*ResponseOk, error)
	Store(ctx context.Context, in *ParamsStore, opts ...grpc.CallOption) (*ResponseOk, error)
	Order(ctx context.Context, in *ParamsOrder, opts ...grpc.CallOption) (*ResponseOk, error)
	Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResponseCategories, error)
	ReasonsByOrder(ctx context.Context, in *ParamsReasonsByOrder, opts ...grpc.CallOption) (*ResponseReasons, error)
	ReasonsByStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResponseReasons, error)
}

type mobileClient struct {
	cc *grpc.ClientConn
}

func NewMobileClient(cc *grpc.ClientConn) MobileClient {
	return &mobileClient{cc}
}

func (c *mobileClient) App(ctx context.Context, in *ParamsApp, opts ...grpc.CallOption) (*ResponseOk, error) {
	out := new(ResponseOk)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/App", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileClient) Store(ctx context.Context, in *ParamsStore, opts ...grpc.CallOption) (*ResponseOk, error) {
	out := new(ResponseOk)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileClient) Order(ctx context.Context, in *ParamsOrder, opts ...grpc.CallOption) (*ResponseOk, error) {
	out := new(ResponseOk)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/Order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileClient) Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResponseCategories, error) {
	out := new(ResponseCategories)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/Categories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileClient) ReasonsByOrder(ctx context.Context, in *ParamsReasonsByOrder, opts ...grpc.CallOption) (*ResponseReasons, error) {
	out := new(ResponseReasons)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/ReasonsByOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileClient) ReasonsByStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResponseReasons, error) {
	out := new(ResponseReasons)
	err := c.cc.Invoke(ctx, "/feedbacks.Mobile/ReasonsByStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobileServer is the server API for Mobile service.
type MobileServer interface {
	App(context.Context, *ParamsApp) (*ResponseOk, error)
	Store(context.Context, *ParamsStore) (*ResponseOk, error)
	Order(context.Context, *ParamsOrder) (*ResponseOk, error)
	Categories(context.Context, *empty.Empty) (*ResponseCategories, error)
	ReasonsByOrder(context.Context, *ParamsReasonsByOrder) (*ResponseReasons, error)
	ReasonsByStore(context.Context, *empty.Empty) (*ResponseReasons, error)
}

// UnimplementedMobileServer can be embedded to have forward compatible implementations.
type UnimplementedMobileServer struct {
}

func (*UnimplementedMobileServer) App(ctx context.Context, req *ParamsApp) (*ResponseOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method App not implemented")
}
func (*UnimplementedMobileServer) Store(ctx context.Context, req *ParamsStore) (*ResponseOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedMobileServer) Order(ctx context.Context, req *ParamsOrder) (*ResponseOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}
func (*UnimplementedMobileServer) Categories(ctx context.Context, req *empty.Empty) (*ResponseCategories, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Categories not implemented")
}
func (*UnimplementedMobileServer) ReasonsByOrder(ctx context.Context, req *ParamsReasonsByOrder) (*ResponseReasons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReasonsByOrder not implemented")
}
func (*UnimplementedMobileServer) ReasonsByStore(ctx context.Context, req *empty.Empty) (*ResponseReasons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReasonsByStore not implemented")
}

func RegisterMobileServer(s *grpc.Server, srv MobileServer) {
	s.RegisterService(&_Mobile_serviceDesc, srv)
}

func _Mobile_App_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsApp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).App(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/App",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).App(ctx, req.(*ParamsApp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mobile_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).Store(ctx, req.(*ParamsStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mobile_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).Order(ctx, req.(*ParamsOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mobile_Categories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).Categories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/Categories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).Categories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mobile_ReasonsByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsReasonsByOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).ReasonsByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/ReasonsByOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).ReasonsByOrder(ctx, req.(*ParamsReasonsByOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mobile_ReasonsByStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).ReasonsByStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedbacks.Mobile/ReasonsByStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).ReasonsByStore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mobile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedbacks.Mobile",
	HandlerType: (*MobileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "App",
			Handler:    _Mobile_App_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Mobile_Store_Handler,
		},
		{
			MethodName: "Order",
			Handler:    _Mobile_Order_Handler,
		},
		{
			MethodName: "Categories",
			Handler:    _Mobile_Categories_Handler,
		},
		{
			MethodName: "ReasonsByOrder",
			Handler:    _Mobile_ReasonsByOrder_Handler,
		},
		{
			MethodName: "ReasonsByStore",
			Handler:    _Mobile_ReasonsByStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/feedbacks.proto",
}
