// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transport_company.proto

package transport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransportCompanyType int32

const (
	TransportCompanyType_boxberry   TransportCompanyType = 0
	TransportCompanyType_cdek       TransportCompanyType = 1
	TransportCompanyType_pochta     TransportCompanyType = 2
	TransportCompanyType_ups        TransportCompanyType = 3
	TransportCompanyType_dpd        TransportCompanyType = 4
	TransportCompanyType_dhl        TransportCompanyType = 5
	TransportCompanyType_redexpress TransportCompanyType = 6
)

var TransportCompanyType_name = map[int32]string{
	0: "boxberry",
	1: "cdek",
	2: "pochta",
	3: "ups",
	4: "dpd",
	5: "dhl",
	6: "redexpress",
}

var TransportCompanyType_value = map[string]int32{
	"boxberry":   0,
	"cdek":       1,
	"pochta":     2,
	"ups":        3,
	"dpd":        4,
	"dhl":        5,
	"redexpress": 6,
}

func (x TransportCompanyType) String() string {
	return proto.EnumName(TransportCompanyType_name, int32(x))
}

func (TransportCompanyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{0}
}

type TransportCompanyToggleParams struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportCompanyToggleParams) Reset()         { *m = TransportCompanyToggleParams{} }
func (m *TransportCompanyToggleParams) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyToggleParams) ProtoMessage()    {}
func (*TransportCompanyToggleParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{0}
}

func (m *TransportCompanyToggleParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyToggleParams.Unmarshal(m, b)
}
func (m *TransportCompanyToggleParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyToggleParams.Marshal(b, m, deterministic)
}
func (m *TransportCompanyToggleParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyToggleParams.Merge(m, src)
}
func (m *TransportCompanyToggleParams) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyToggleParams.Size(m)
}
func (m *TransportCompanyToggleParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyToggleParams.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyToggleParams proto.InternalMessageInfo

func (m *TransportCompanyToggleParams) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransportCompanyToggleParams) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type TransportCompanyGetResponse struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 TransportCompanyType `protobuf:"varint,3,opt,name=type,proto3,enum=transport.TransportCompanyType" json:"type,omitempty"`
	IsActive             bool                 `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Created              string               `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string               `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransportCompanyGetResponse) Reset()         { *m = TransportCompanyGetResponse{} }
func (m *TransportCompanyGetResponse) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyGetResponse) ProtoMessage()    {}
func (*TransportCompanyGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{1}
}

func (m *TransportCompanyGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyGetResponse.Unmarshal(m, b)
}
func (m *TransportCompanyGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyGetResponse.Marshal(b, m, deterministic)
}
func (m *TransportCompanyGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyGetResponse.Merge(m, src)
}
func (m *TransportCompanyGetResponse) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyGetResponse.Size(m)
}
func (m *TransportCompanyGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyGetResponse proto.InternalMessageInfo

func (m *TransportCompanyGetResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransportCompanyGetResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TransportCompanyGetResponse) GetType() TransportCompanyType {
	if m != nil {
		return m.Type
	}
	return TransportCompanyType_boxberry
}

func (m *TransportCompanyGetResponse) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *TransportCompanyGetResponse) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *TransportCompanyGetResponse) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type TransportCompanyID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportCompanyID) Reset()         { *m = TransportCompanyID{} }
func (m *TransportCompanyID) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyID) ProtoMessage()    {}
func (*TransportCompanyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{2}
}

func (m *TransportCompanyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyID.Unmarshal(m, b)
}
func (m *TransportCompanyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyID.Marshal(b, m, deterministic)
}
func (m *TransportCompanyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyID.Merge(m, src)
}
func (m *TransportCompanyID) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyID.Size(m)
}
func (m *TransportCompanyID) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyID.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyID proto.InternalMessageInfo

func (m *TransportCompanyID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TransportCompanyAddParams struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type                 TransportCompanyType `protobuf:"varint,2,opt,name=type,proto3,enum=transport.TransportCompanyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransportCompanyAddParams) Reset()         { *m = TransportCompanyAddParams{} }
func (m *TransportCompanyAddParams) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyAddParams) ProtoMessage()    {}
func (*TransportCompanyAddParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{3}
}

func (m *TransportCompanyAddParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyAddParams.Unmarshal(m, b)
}
func (m *TransportCompanyAddParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyAddParams.Marshal(b, m, deterministic)
}
func (m *TransportCompanyAddParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyAddParams.Merge(m, src)
}
func (m *TransportCompanyAddParams) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyAddParams.Size(m)
}
func (m *TransportCompanyAddParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyAddParams.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyAddParams proto.InternalMessageInfo

func (m *TransportCompanyAddParams) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TransportCompanyAddParams) GetType() TransportCompanyType {
	if m != nil {
		return m.Type
	}
	return TransportCompanyType_boxberry
}

type TransportCompanyUpdateParams struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 TransportCompanyType `protobuf:"varint,3,opt,name=type,proto3,enum=transport.TransportCompanyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransportCompanyUpdateParams) Reset()         { *m = TransportCompanyUpdateParams{} }
func (m *TransportCompanyUpdateParams) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyUpdateParams) ProtoMessage()    {}
func (*TransportCompanyUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{4}
}

func (m *TransportCompanyUpdateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyUpdateParams.Unmarshal(m, b)
}
func (m *TransportCompanyUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyUpdateParams.Marshal(b, m, deterministic)
}
func (m *TransportCompanyUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyUpdateParams.Merge(m, src)
}
func (m *TransportCompanyUpdateParams) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyUpdateParams.Size(m)
}
func (m *TransportCompanyUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyUpdateParams proto.InternalMessageInfo

func (m *TransportCompanyUpdateParams) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransportCompanyUpdateParams) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TransportCompanyUpdateParams) GetType() TransportCompanyType {
	if m != nil {
		return m.Type
	}
	return TransportCompanyType_boxberry
}

type TransportCompanyOkResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportCompanyOkResponse) Reset()         { *m = TransportCompanyOkResponse{} }
func (m *TransportCompanyOkResponse) String() string { return proto.CompactTextString(m) }
func (*TransportCompanyOkResponse) ProtoMessage()    {}
func (*TransportCompanyOkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d0e24739b69be1, []int{5}
}

func (m *TransportCompanyOkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportCompanyOkResponse.Unmarshal(m, b)
}
func (m *TransportCompanyOkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportCompanyOkResponse.Marshal(b, m, deterministic)
}
func (m *TransportCompanyOkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportCompanyOkResponse.Merge(m, src)
}
func (m *TransportCompanyOkResponse) XXX_Size() int {
	return xxx_messageInfo_TransportCompanyOkResponse.Size(m)
}
func (m *TransportCompanyOkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportCompanyOkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransportCompanyOkResponse proto.InternalMessageInfo

func (m *TransportCompanyOkResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterEnum("transport.TransportCompanyType", TransportCompanyType_name, TransportCompanyType_value)
	proto.RegisterType((*TransportCompanyToggleParams)(nil), "transport.TransportCompanyToggleParams")
	proto.RegisterType((*TransportCompanyGetResponse)(nil), "transport.TransportCompanyGetResponse")
	proto.RegisterType((*TransportCompanyID)(nil), "transport.TransportCompanyID")
	proto.RegisterType((*TransportCompanyAddParams)(nil), "transport.TransportCompanyAddParams")
	proto.RegisterType((*TransportCompanyUpdateParams)(nil), "transport.TransportCompanyUpdateParams")
	proto.RegisterType((*TransportCompanyOkResponse)(nil), "transport.TransportCompanyOkResponse")
}

func init() { proto.RegisterFile("proto/transport_company.proto", fileDescriptor_64d0e24739b69be1) }

var fileDescriptor_64d0e24739b69be1 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0x8d, 0xed, 0xc4, 0x75, 0x2e, 0x25, 0x88, 0x4b, 0x1f, 0xbc, 0x74, 0x65, 0x41, 0x74, 0x5b,
	0x18, 0x23, 0x83, 0xf6, 0x0b, 0xba, 0x06, 0x4a, 0x19, 0xac, 0xc5, 0x74, 0x2f, 0x79, 0x29, 0x8e,
	0x75, 0x97, 0x9a, 0xa4, 0x91, 0x90, 0xd4, 0x51, 0x7f, 0xdc, 0x3e, 0x60, 0x7f, 0x35, 0x2a, 0xb7,
	0x9e, 0xeb, 0x74, 0x5e, 0x07, 0x7d, 0xd3, 0xf5, 0x39, 0x3e, 0xf7, 0x5c, 0x1d, 0x71, 0x61, 0x4f,
	0x69, 0x69, 0xe5, 0x27, 0xab, 0xd3, 0xb5, 0x51, 0x52, 0xdb, 0xcb, 0x4c, 0x5e, 0xab, 0x74, 0x5d,
	0x4c, 0xdc, 0x77, 0xec, 0x57, 0x00, 0xff, 0x02, 0xaf, 0x2f, 0x1e, 0x8a, 0xe3, 0x92, 0x74, 0x21,
	0x17, 0x8b, 0x15, 0x9d, 0xa7, 0x3a, 0xbd, 0x36, 0x38, 0x00, 0x3f, 0x17, 0xb1, 0x37, 0xf2, 0xc6,
	0xbd, 0xc4, 0xcf, 0x05, 0xee, 0x42, 0x3f, 0x37, 0x97, 0x69, 0x66, 0xf3, 0x1f, 0x14, 0xfb, 0x23,
	0x6f, 0x1c, 0x25, 0x51, 0x6e, 0x8e, 0x5c, 0xcd, 0x7f, 0x79, 0xb0, 0xdb, 0x54, 0x3b, 0x21, 0x9b,
	0x90, 0x51, 0x72, 0x6d, 0x68, 0x43, 0x6c, 0x07, 0x7a, 0x36, 0xb7, 0xab, 0x52, 0xa8, 0x9f, 0x94,
	0x05, 0x1e, 0x42, 0xd7, 0x16, 0x8a, 0xe2, 0x60, 0xe4, 0x8d, 0x07, 0x07, 0x6f, 0x26, 0x95, 0xd9,
	0xc9, 0x86, 0xd3, 0x42, 0x51, 0xe2, 0xc8, 0x8f, 0x7d, 0x75, 0x1f, 0xfb, 0xc2, 0x18, 0xb6, 0x32,
	0x4d, 0xa9, 0x25, 0x11, 0xf7, 0x5c, 0xa7, 0x87, 0xf2, 0x0e, 0xb9, 0x51, 0xc2, 0x21, 0x61, 0x89,
	0xdc, 0x97, 0x7c, 0x1f, 0xb0, 0xd9, 0xee, 0x74, 0xda, 0x9c, 0x80, 0x7f, 0x87, 0x57, 0x4d, 0xd6,
	0x91, 0x10, 0xf7, 0x77, 0x57, 0x8d, 0xe7, 0x3d, 0x35, 0x9e, 0xff, 0x1f, 0xe3, 0xf1, 0x62, 0x33,
	0xa6, 0x6f, 0xce, 0xe8, 0x5f, 0x62, 0x7a, 0xb9, 0x9b, 0xe5, 0x1f, 0x61, 0xd8, 0x44, 0xcf, 0x96,
	0xf5, 0x48, 0xe5, 0xd2, 0x35, 0x8e, 0x12, 0x5f, 0x2e, 0x3f, 0x10, 0xec, 0x3c, 0xa5, 0x85, 0xdb,
	0x10, 0xcd, 0xe5, 0xed, 0x9c, 0xb4, 0x2e, 0x58, 0x07, 0x23, 0xe8, 0x66, 0x82, 0x96, 0xcc, 0x43,
	0x80, 0x50, 0xc9, 0xec, 0xca, 0xa6, 0xcc, 0xc7, 0x2d, 0x08, 0x6e, 0x94, 0x61, 0xc1, 0xdd, 0x41,
	0x28, 0xc1, 0xba, 0xee, 0x70, 0xb5, 0x62, 0x3d, 0x1c, 0x00, 0x68, 0x12, 0x74, 0xab, 0x34, 0x19,
	0xc3, 0xc2, 0x83, 0x9f, 0x01, 0xb0, 0x66, 0x1f, 0x3c, 0x83, 0xf0, 0xd8, 0xe5, 0x8a, 0xfb, 0x2d,
	0xa3, 0x55, 0xf9, 0x0c, 0xf7, 0x5a, 0x58, 0xa7, 0x53, 0xde, 0xc1, 0xaf, 0x10, 0x9c, 0x90, 0xc5,
	0x76, 0xde, 0xf0, 0x5d, 0x0b, 0x5c, 0x7b, 0xfd, 0xbc, 0x83, 0x33, 0x08, 0xcb, 0xd4, 0xf0, 0x7d,
	0xcb, 0x3f, 0xf5, 0x60, 0x87, 0x6f, 0x5b, 0x88, 0x7f, 0x62, 0xe0, 0x1d, 0x3c, 0x87, 0x70, 0x4a,
	0x2b, 0xb2, 0xf4, 0x2f, 0xbb, 0xcf, 0x56, 0x9c, 0x41, 0x58, 0xae, 0x82, 0x56, 0xb7, 0xf5, 0x6d,
	0xf1, 0x6c, 0xed, 0xcf, 0x83, 0xd9, 0xf6, 0xa2, 0xb6, 0x9f, 0xe6, 0xa1, 0x5b, 0x4c, 0x87, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x40, 0xf4, 0x1c, 0xb9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransportCompanyClient is the client API for TransportCompany service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransportCompanyClient interface {
	Create(ctx context.Context, in *TransportCompanyAddParams, opts ...grpc.CallOption) (*TransportCompanyID, error)
	Get(ctx context.Context, in *TransportCompanyID, opts ...grpc.CallOption) (*TransportCompanyGetResponse, error)
	Update(ctx context.Context, in *TransportCompanyUpdateParams, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error)
	Delete(ctx context.Context, in *TransportCompanyID, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error)
	Toggle(ctx context.Context, in *TransportCompanyToggleParams, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error)
}

type transportCompanyClient struct {
	cc *grpc.ClientConn
}

func NewTransportCompanyClient(cc *grpc.ClientConn) TransportCompanyClient {
	return &transportCompanyClient{cc}
}

func (c *transportCompanyClient) Create(ctx context.Context, in *TransportCompanyAddParams, opts ...grpc.CallOption) (*TransportCompanyID, error) {
	out := new(TransportCompanyID)
	err := c.cc.Invoke(ctx, "/transport.TransportCompany/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportCompanyClient) Get(ctx context.Context, in *TransportCompanyID, opts ...grpc.CallOption) (*TransportCompanyGetResponse, error) {
	out := new(TransportCompanyGetResponse)
	err := c.cc.Invoke(ctx, "/transport.TransportCompany/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportCompanyClient) Update(ctx context.Context, in *TransportCompanyUpdateParams, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error) {
	out := new(TransportCompanyOkResponse)
	err := c.cc.Invoke(ctx, "/transport.TransportCompany/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportCompanyClient) Delete(ctx context.Context, in *TransportCompanyID, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error) {
	out := new(TransportCompanyOkResponse)
	err := c.cc.Invoke(ctx, "/transport.TransportCompany/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportCompanyClient) Toggle(ctx context.Context, in *TransportCompanyToggleParams, opts ...grpc.CallOption) (*TransportCompanyOkResponse, error) {
	out := new(TransportCompanyOkResponse)
	err := c.cc.Invoke(ctx, "/transport.TransportCompany/Toggle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransportCompanyServer is the server API for TransportCompany service.
type TransportCompanyServer interface {
	Create(context.Context, *TransportCompanyAddParams) (*TransportCompanyID, error)
	Get(context.Context, *TransportCompanyID) (*TransportCompanyGetResponse, error)
	Update(context.Context, *TransportCompanyUpdateParams) (*TransportCompanyOkResponse, error)
	Delete(context.Context, *TransportCompanyID) (*TransportCompanyOkResponse, error)
	Toggle(context.Context, *TransportCompanyToggleParams) (*TransportCompanyOkResponse, error)
}

// UnimplementedTransportCompanyServer can be embedded to have forward compatible implementations.
type UnimplementedTransportCompanyServer struct {
}

func (*UnimplementedTransportCompanyServer) Create(ctx context.Context, req *TransportCompanyAddParams) (*TransportCompanyID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTransportCompanyServer) Get(ctx context.Context, req *TransportCompanyID) (*TransportCompanyGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTransportCompanyServer) Update(ctx context.Context, req *TransportCompanyUpdateParams) (*TransportCompanyOkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedTransportCompanyServer) Delete(ctx context.Context, req *TransportCompanyID) (*TransportCompanyOkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedTransportCompanyServer) Toggle(ctx context.Context, req *TransportCompanyToggleParams) (*TransportCompanyOkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Toggle not implemented")
}

func RegisterTransportCompanyServer(s *grpc.Server, srv TransportCompanyServer) {
	s.RegisterService(&_TransportCompany_serviceDesc, srv)
}

func _TransportCompany_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportCompanyAddParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportCompanyServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TransportCompany/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportCompanyServer).Create(ctx, req.(*TransportCompanyAddParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportCompany_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportCompanyID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportCompanyServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TransportCompany/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportCompanyServer).Get(ctx, req.(*TransportCompanyID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportCompany_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportCompanyUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportCompanyServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TransportCompany/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportCompanyServer).Update(ctx, req.(*TransportCompanyUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportCompany_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportCompanyID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportCompanyServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TransportCompany/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportCompanyServer).Delete(ctx, req.(*TransportCompanyID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportCompany_Toggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportCompanyToggleParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportCompanyServer).Toggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TransportCompany/Toggle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportCompanyServer).Toggle(ctx, req.(*TransportCompanyToggleParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransportCompany_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transport.TransportCompany",
	HandlerType: (*TransportCompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TransportCompany_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TransportCompany_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TransportCompany_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TransportCompany_Delete_Handler,
		},
		{
			MethodName: "Toggle",
			Handler:    _TransportCompany_Toggle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transport_company.proto",
}
